const SET_ALL_COUNTRIES='SET_ALL_COUNTRIES';
const GET_ALL_COUNTRIES='GET_ALL_COUNTRIES';
const GET_COUNTRY='GET_COUNTRIE';
const SET_COUNTRY='SET_COUNTRIE';
const SET_SELECT_REGION='SET_SELECT_REGION';
export {SET_ALL_COUNTRIES,GET_COUNTRY,GET_ALL_COUNTRIES,SET_COUNTRY,SET_SELECT_REGION}